export const TOOL_ITEMS = {
    BRUSH: "BRUSH",
    LINE: "LINE",
    RECTANGLE: "RECTANGLE",
    CIRCLE: "CIRCLE",
    ARROW: "ARROW",
    ERASER: "ERASER",
};

export const BOARD_ACTION = {
    CHANGE_TOOL: "CHANGE_TOOL",
    DRAW_DOWN: "DRAW_DOWN",
    DRAW_MOVE: "DRAW_MOVE",
    DRAW_UP: "DRAW_UP",
    ERASE: "ERASE",
    CHANGE_ACTION_TYPE: "CHANGE_ACTION_TYPE",
};

export const TOOL_ACTION_TYPES = {
    NONE: "NONE",
    DRAWING: "DRAWING",
    ERASING: "ERASING",
};

export const COLORS = {
    BLACK: "#000000",
    RED: "#ff0000",
    GREEN: "#00ff00",
    BLUE: "#0000ff",
    ORANGE: "#ffa500",
    YELLOW: "#ffff00",
    WHITE: "#ffffff",
};

export const TOOLBOX_ACTION = {
    CHANGE_STROKE: "CHANGE_STROKE",
    CHANGE_FILL: "CHANGE_FILL",
    CHANGE_SIZE: "CHANGE_SIZE",
};

export const FILL_TOOL_ITEMS = [TOOL_ITEMS.CIRCLE, TOOL_ITEMS.RECTANGLE];

export const STROKE_TOOL_ITEMS = [TOOL_ITEMS.BRUSH, TOOL_ITEMS.ARROW, TOOL_ITEMS.CIRCLE, TOOL_ITEMS.LINE, TOOL_ITEMS.RECTANGLE];

export const SIZE_TOOL_ITEMS = [TOOL_ITEMS.ARROW, TOOL_ITEMS.CIRCLE, TOOL_ITEMS.LINE, TOOL_ITEMS.RECTANGLE];

export const ARROW_LENGTH = 20;

export const ELEMENT_ERASE_THRESHOLD = 0.1